version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: incidents
      POSTGRES_USER: incident
      POSTGRES_PASSWORD: incident
    ports:
      - "5432:5432"

  ingest-service:
    build: ./ingest-service
    depends_on:
      - postgres
